// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VidyaAI.Infrastructure.Data;

#nullable disable

namespace VidyaAI.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260503195752_AddRoleDefinitions")]
    partial class AddRoleDefinitions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VidyaAI.Domain.Entities.Announcement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("SchoolId");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AiSummary")
                        .HasColumnType("text");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<string>("Tags")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer");

                    b.Property<string>("YoutubeUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PublishedAt");

                    b.HasIndex("SchoolId");

                    b.HasIndex("Status");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("IconUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 5, 3, 19, 57, 51, 639, DateTimeKind.Utc).AddTicks(2107),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Technology",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 5, 3, 19, 57, 51, 639, DateTimeKind.Utc).AddTicks(2111),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Science",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 5, 3, 19, 57, 51, 639, DateTimeKind.Utc).AddTicks(2114),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "General Knowledge",
                            SortOrder = 3
                        });
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("LikeCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ParentCommentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.CommentLike", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("CommentId", "UserId")
                        .IsUnique();

                    b.ToTable("CommentLikes");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.Like", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ArticleId", "UserId")
                        .IsUnique();

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReferenceId")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsRead");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.RoleDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("RoleDefinitions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 5, 3, 19, 57, 51, 639, DateTimeKind.Utc).AddTicks(2599),
                            Description = "Global platform owner with full operational control.",
                            DisplayName = "Super Admin",
                            IsActive = true,
                            IsDeleted = false,
                            IsSystemRole = true,
                            Name = "SuperAdmin"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 5, 3, 19, 57, 51, 639, DateTimeKind.Utc).AddTicks(2604),
                            Description = "Manages one school, its users, content, and operations.",
                            DisplayName = "School Admin",
                            IsActive = true,
                            IsDeleted = false,
                            IsSystemRole = true,
                            Name = "SchoolAdmin"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 5, 3, 19, 57, 51, 639, DateTimeKind.Utc).AddTicks(2608),
                            Description = "Creates learning content and supports study workflows.",
                            DisplayName = "Teacher",
                            IsActive = true,
                            IsDeleted = false,
                            IsSystemRole = true,
                            Name = "Teacher"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 5, 3, 19, 57, 51, 639, DateTimeKind.Utc).AddTicks(2613),
                            Description = "Learner workspace for study materials and practice.",
                            DisplayName = "Student",
                            IsActive = true,
                            IsDeleted = false,
                            IsSystemRole = true,
                            Name = "Student"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 5, 3, 19, 57, 51, 639, DateTimeKind.Utc).AddTicks(2616),
                            Description = "Guardian view into school learning content.",
                            DisplayName = "Parent",
                            IsActive = true,
                            IsDeleted = false,
                            IsSystemRole = true,
                            Name = "Parent"
                        });
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CanApprove")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanCreate")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanDelete")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanEdit")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanView")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Role", "Module")
                        .IsUnique();

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            CanApprove = true,
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            CreatedAt = new DateTime(2026, 5, 3, 19, 57, 51, 639, DateTimeKind.Utc).AddTicks(2390),
                            IsDeleted = false,
                            Module = "Dashboard",
                            Role = "SuperAdmin"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            CanApprove = true,
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            CreatedAt = new DateTime(2026, 5, 3, 19, 57, 51, 639, DateTimeKind.Utc).AddTicks(2399),
                            IsDeleted = false,
                            Module = "Schools",
                            Role = "SuperAdmin"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            CanApprove = true,
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            CreatedAt = new DateTime(2026, 5, 3, 19, 57, 51, 639, DateTimeKind.Utc).AddTicks(2405),
                            IsDeleted = false,
                            Module = "Users",
                            Role = "SuperAdmin"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            CanApprove = true,
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            CreatedAt = new DateTime(2026, 5, 3, 19, 57, 51, 639, DateTimeKind.Utc).AddTicks(2410),
                            IsDeleted = false,
                            Module = "Roles",
                            Role = "SuperAdmin"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            CanApprove = true,
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            CreatedAt = new DateTime(2026, 5, 3, 19, 57, 51, 639, DateTimeKind.Utc).AddTicks(2418),
                            IsDeleted = false,
                            Module = "Articles",
                            Role = "SuperAdmin"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            CanApprove = true,
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            CreatedAt = new DateTime(2026, 5, 3, 19, 57, 51, 639, DateTimeKind.Utc).AddTicks(2425),
                            IsDeleted = false,
                            Module = "Categories",
                            Role = "SuperAdmin"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            CanApprove = false,
                            CanCreate = false,
                            CanDelete = false,
                            CanEdit = false,
                            CanView = true,
                            CreatedAt = new DateTime(2026, 5, 3, 19, 57, 51, 639, DateTimeKind.Utc).AddTicks(2430),
                            IsDeleted = false,
                            Module = "Dashboard",
                            Role = "SchoolAdmin"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            CanApprove = false,
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            CreatedAt = new DateTime(2026, 5, 3, 19, 57, 51, 639, DateTimeKind.Utc).AddTicks(2436),
                            IsDeleted = false,
                            Module = "Users",
                            Role = "SchoolAdmin"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            CanApprove = false,
                            CanCreate = false,
                            CanDelete = false,
                            CanEdit = false,
                            CanView = true,
                            CreatedAt = new DateTime(2026, 5, 3, 19, 57, 51, 639, DateTimeKind.Utc).AddTicks(2441),
                            IsDeleted = false,
                            Module = "Roles",
                            Role = "SchoolAdmin"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000010"),
                            CanApprove = true,
                            CanCreate = true,
                            CanDelete = false,
                            CanEdit = true,
                            CanView = true,
                            CreatedAt = new DateTime(2026, 5, 3, 19, 57, 51, 639, DateTimeKind.Utc).AddTicks(2448),
                            IsDeleted = false,
                            Module = "Articles",
                            Role = "SchoolAdmin"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000011"),
                            CanApprove = false,
                            CanCreate = true,
                            CanDelete = false,
                            CanEdit = true,
                            CanView = true,
                            CreatedAt = new DateTime(2026, 5, 3, 19, 57, 51, 639, DateTimeKind.Utc).AddTicks(2453),
                            IsDeleted = false,
                            Module = "Categories",
                            Role = "SchoolAdmin"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000012"),
                            CanApprove = false,
                            CanCreate = false,
                            CanDelete = false,
                            CanEdit = false,
                            CanView = true,
                            CreatedAt = new DateTime(2026, 5, 3, 19, 57, 51, 639, DateTimeKind.Utc).AddTicks(2458),
                            IsDeleted = false,
                            Module = "Dashboard",
                            Role = "Teacher"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000013"),
                            CanApprove = false,
                            CanCreate = true,
                            CanDelete = false,
                            CanEdit = true,
                            CanView = true,
                            CreatedAt = new DateTime(2026, 5, 3, 19, 57, 51, 639, DateTimeKind.Utc).AddTicks(2466),
                            IsDeleted = false,
                            Module = "Articles",
                            Role = "Teacher"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000014"),
                            CanApprove = false,
                            CanCreate = false,
                            CanDelete = false,
                            CanEdit = false,
                            CanView = true,
                            CreatedAt = new DateTime(2026, 5, 3, 19, 57, 51, 639, DateTimeKind.Utc).AddTicks(2470),
                            IsDeleted = false,
                            Module = "Categories",
                            Role = "Teacher"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000015"),
                            CanApprove = false,
                            CanCreate = false,
                            CanDelete = false,
                            CanEdit = false,
                            CanView = true,
                            CreatedAt = new DateTime(2026, 5, 3, 19, 57, 51, 639, DateTimeKind.Utc).AddTicks(2474),
                            IsDeleted = false,
                            Module = "Dashboard",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000016"),
                            CanApprove = false,
                            CanCreate = false,
                            CanDelete = false,
                            CanEdit = false,
                            CanView = true,
                            CreatedAt = new DateTime(2026, 5, 3, 19, 57, 51, 639, DateTimeKind.Utc).AddTicks(2479),
                            IsDeleted = false,
                            Module = "Articles",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000017"),
                            CanApprove = false,
                            CanCreate = false,
                            CanDelete = false,
                            CanEdit = false,
                            CanView = true,
                            CreatedAt = new DateTime(2026, 5, 3, 19, 57, 51, 639, DateTimeKind.Utc).AddTicks(2483),
                            IsDeleted = false,
                            Module = "Categories",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000018"),
                            CanApprove = false,
                            CanCreate = false,
                            CanDelete = false,
                            CanEdit = false,
                            CanView = true,
                            CreatedAt = new DateTime(2026, 5, 3, 19, 57, 51, 639, DateTimeKind.Utc).AddTicks(2489),
                            IsDeleted = false,
                            Module = "Dashboard",
                            Role = "Parent"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000019"),
                            CanApprove = false,
                            CanCreate = false,
                            CanDelete = false,
                            CanEdit = false,
                            CanView = true,
                            CreatedAt = new DateTime(2026, 5, 3, 19, 57, 51, 639, DateTimeKind.Utc).AddTicks(2493),
                            IsDeleted = false,
                            Module = "Articles",
                            Role = "Parent"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000020"),
                            CanApprove = false,
                            CanCreate = false,
                            CanDelete = false,
                            CanEdit = false,
                            CanView = true,
                            CreatedAt = new DateTime(2026, 5, 3, 19, 57, 51, 639, DateTimeKind.Utc).AddTicks(2498),
                            IsDeleted = false,
                            Module = "Categories",
                            Role = "Parent"
                        });
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.School", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Board")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SubscriptionExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SubscriptionStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Schools");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Board = "CBSE",
                            City = "Srinagar",
                            CreatedAt = new DateTime(2026, 5, 3, 19, 57, 51, 639, DateTimeKind.Utc).AddTicks(1615),
                            Email = "demo@codestrix.com",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "CodeStrix Demo School",
                            Plan = "Pro",
                            State = "J&K",
                            SubscriptionExpiresAt = new DateTime(2027, 5, 3, 19, 57, 51, 639, DateTimeKind.Utc).AddTicks(1565),
                            SubscriptionStatus = "Active",
                            Type = "Private"
                        });
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("SchoolId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 5, 3, 19, 57, 51, 639, DateTimeKind.Utc).AddTicks(1943),
                            Email = "admin@vidyaai.com",
                            EmailVerified = true,
                            FirstName = "Super",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Admin",
                            PasswordHash = "$2a$11$RIzKRlsKF6lh3k9LHQHsROIDjily/9oaxg5wL8JSVdSxmBRQv7WVm",
                            Role = "SuperAdmin",
                            SchoolId = new Guid("00000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 5, 3, 19, 57, 51, 639, DateTimeKind.Utc).AddTicks(1949),
                            Email = "schooladmin@vidyaai.com",
                            EmailVerified = true,
                            FirstName = "Aaliya",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Khan",
                            PasswordHash = "$2a$11$RIzKRlsKF6lh3k9LHQHsROIDjily/9oaxg5wL8JSVdSxmBRQv7WVm",
                            Role = "SchoolAdmin",
                            SchoolId = new Guid("00000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 5, 3, 19, 57, 51, 639, DateTimeKind.Utc).AddTicks(1954),
                            Email = "teacher@vidyaai.com",
                            EmailVerified = true,
                            FirstName = "Rohan",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Sharma",
                            PasswordHash = "$2a$11$RIzKRlsKF6lh3k9LHQHsROIDjily/9oaxg5wL8JSVdSxmBRQv7WVm",
                            Role = "Teacher",
                            SchoolId = new Guid("00000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2026, 5, 3, 19, 57, 51, 639, DateTimeKind.Utc).AddTicks(1959),
                            Email = "student@vidyaai.com",
                            EmailVerified = true,
                            FirstName = "Zoya",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Mir",
                            PasswordHash = "$2a$11$RIzKRlsKF6lh3k9LHQHsROIDjily/9oaxg5wL8JSVdSxmBRQv7WVm",
                            Role = "Student",
                            SchoolId = new Guid("00000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTime(2026, 5, 3, 19, 57, 51, 639, DateTimeKind.Utc).AddTicks(1977),
                            Email = "parent@vidyaai.com",
                            EmailVerified = true,
                            FirstName = "Imran",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Mir",
                            PasswordHash = "$2a$11$RIzKRlsKF6lh3k9LHQHsROIDjily/9oaxg5wL8JSVdSxmBRQv7WVm",
                            Role = "Parent",
                            SchoolId = new Guid("00000000-0000-0000-0000-000000000002")
                        });
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.UserPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId", "CategoryId")
                        .IsUnique();

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.UserSchoolEnrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.HasIndex("UserId", "SchoolId", "Role")
                        .IsUnique();

                    b.ToTable("UserSchoolEnrollments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 5, 3, 19, 57, 51, 639, DateTimeKind.Utc).AddTicks(2995),
                            EnrolledAt = new DateTime(2026, 5, 3, 19, 57, 51, 639, DateTimeKind.Utc).AddTicks(2994),
                            IsDeleted = false,
                            IsPrimary = true,
                            Role = "SuperAdmin",
                            SchoolId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Status = "Active",
                            UserId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 5, 3, 19, 57, 51, 639, DateTimeKind.Utc).AddTicks(3011),
                            EnrolledAt = new DateTime(2026, 5, 3, 19, 57, 51, 639, DateTimeKind.Utc).AddTicks(3010),
                            IsDeleted = false,
                            IsPrimary = true,
                            Role = "SchoolAdmin",
                            SchoolId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Status = "Active",
                            UserId = new Guid("00000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 5, 3, 19, 57, 51, 639, DateTimeKind.Utc).AddTicks(3018),
                            EnrolledAt = new DateTime(2026, 5, 3, 19, 57, 51, 639, DateTimeKind.Utc).AddTicks(3017),
                            IsDeleted = false,
                            IsPrimary = true,
                            Role = "Teacher",
                            SchoolId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Status = "Active",
                            UserId = new Guid("00000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 5, 3, 19, 57, 51, 639, DateTimeKind.Utc).AddTicks(3031),
                            EnrolledAt = new DateTime(2026, 5, 3, 19, 57, 51, 639, DateTimeKind.Utc).AddTicks(3031),
                            IsDeleted = false,
                            IsPrimary = true,
                            Role = "Student",
                            SchoolId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Status = "Active",
                            UserId = new Guid("00000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 5, 3, 19, 57, 51, 639, DateTimeKind.Utc).AddTicks(3101),
                            EnrolledAt = new DateTime(2026, 5, 3, 19, 57, 51, 639, DateTimeKind.Utc).AddTicks(3101),
                            IsDeleted = false,
                            IsPrimary = true,
                            Role = "Parent",
                            SchoolId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Status = "Active",
                            UserId = new Guid("00000000-0000-0000-0000-000000000009")
                        });
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.Announcement", b =>
                {
                    b.HasOne("VidyaAI.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VidyaAI.Domain.Entities.School", "School")
                        .WithMany("Announcements")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("School");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.Article", b =>
                {
                    b.HasOne("VidyaAI.Domain.Entities.User", "Author")
                        .WithMany("Articles")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VidyaAI.Domain.Entities.Category", "Category")
                        .WithMany("Articles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VidyaAI.Domain.Entities.School", "School")
                        .WithMany("Articles")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Author");

                    b.Navigation("Category");

                    b.Navigation("School");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.Comment", b =>
                {
                    b.HasOne("VidyaAI.Domain.Entities.Article", "Article")
                        .WithMany("Comments")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VidyaAI.Domain.Entities.Comment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VidyaAI.Domain.Entities.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("ParentComment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.CommentLike", b =>
                {
                    b.HasOne("VidyaAI.Domain.Entities.Comment", "Comment")
                        .WithMany("CommentLikes")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VidyaAI.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.Like", b =>
                {
                    b.HasOne("VidyaAI.Domain.Entities.Article", "Article")
                        .WithMany("Likes")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VidyaAI.Domain.Entities.User", "User")
                        .WithMany("Likes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.Notification", b =>
                {
                    b.HasOne("VidyaAI.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.User", b =>
                {
                    b.HasOne("VidyaAI.Domain.Entities.School", "School")
                        .WithMany("Users")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("School");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.UserPreference", b =>
                {
                    b.HasOne("VidyaAI.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VidyaAI.Domain.Entities.User", "User")
                        .WithMany("Preferences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.UserSchoolEnrollment", b =>
                {
                    b.HasOne("VidyaAI.Domain.Entities.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VidyaAI.Domain.Entities.User", "User")
                        .WithMany("Enrollments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.Article", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Likes");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.Category", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.Comment", b =>
                {
                    b.Navigation("CommentLikes");

                    b.Navigation("Replies");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.School", b =>
                {
                    b.Navigation("Announcements");

                    b.Navigation("Articles");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.User", b =>
                {
                    b.Navigation("Articles");

                    b.Navigation("Comments");

                    b.Navigation("Enrollments");

                    b.Navigation("Likes");

                    b.Navigation("Preferences");
                });
#pragma warning restore 612, 618
        }
    }
}
