// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VidyaAI.Infrastructure.Data;

#nullable disable

namespace VidyaAI.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260611111839_AddNarrationKind")]
    partial class AddNarrationKind
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VidyaAI.Domain.Entities.Announcement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("SchoolId");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AiSummary")
                        .HasColumnType("text");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<string>("Tags")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer");

                    b.Property<string>("YoutubeUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PublishedAt");

                    b.HasIndex("SchoolId");

                    b.HasIndex("Status");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("IconUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 6, 11, 11, 18, 38, 809, DateTimeKind.Utc).AddTicks(520),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Technology",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 6, 11, 11, 18, 38, 809, DateTimeKind.Utc).AddTicks(520),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Science",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 6, 11, 11, 18, 38, 809, DateTimeKind.Utc).AddTicks(520),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "General Knowledge",
                            SortOrder = 3
                        });
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CitedChunkIds")
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.ChatSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("MaterialId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("UserId");

                    b.ToTable("ChatSessions");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("LikeCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ParentCommentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.CommentLike", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("CommentId", "UserId")
                        .IsUnique();

                    b.ToTable("CommentLikes");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.Delivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FlashcardSetId")
                        .HasColumnType("uuid");

                    b.Property<string>("GradeLevel")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Instructions")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("MaterialId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("QuizId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("ScheduledDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("FlashcardSetId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("QuizId");

                    b.HasIndex("SchoolId", "ScheduledDate");

                    b.ToTable("Deliveries");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.Flashcard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Back")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Front")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("SetId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SourceChunkId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SetId");

                    b.ToTable("Flashcards");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.FlashcardSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CardCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("MaterialId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("MaterialId");

                    b.HasIndex("SchoolId");

                    b.ToTable("FlashcardSets");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.LessonPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentMarkdown")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("GradeLevel")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("MaterialId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<string>("Subject")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("MaterialId");

                    b.HasIndex("SchoolId");

                    b.ToTable("LessonPlans");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.Like", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ArticleId", "UserId")
                        .IsUnique();

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("PageCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UploadedById")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SchoolId");

                    b.HasIndex("UploadedById");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.MaterialChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float[]>("Embedding")
                        .HasColumnType("real[]");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uuid");

                    b.Property<int?>("PageNumber")
                        .HasColumnType("integer");

                    b.Property<int>("TokenCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("MaterialId", "ChunkIndex")
                        .IsUnique();

                    b.ToTable("MaterialChunks");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.Narration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AudioUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Voice")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId", "Kind")
                        .IsUnique();

                    b.ToTable("Narrations");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.NarrationSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EndMs")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("NarrationId")
                        .HasColumnType("uuid");

                    b.Property<int?>("PageNumber")
                        .HasColumnType("integer");

                    b.Property<int>("SegmentIndex")
                        .HasColumnType("integer");

                    b.Property<int>("StartMs")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NarrationId");

                    b.HasIndex("NarrationId", "SegmentIndex")
                        .IsUnique();

                    b.ToTable("NarrationSegments");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReferenceId")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsRead");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.Quiz", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("MaterialId")
                        .HasColumnType("uuid");

                    b.Property<int>("QuestionCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("MaterialId");

                    b.HasIndex("SchoolId");

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.QuizAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnswersJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uuid");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.HasIndex("UserId");

                    b.ToTable("QuizAttempts");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.QuizQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CorrectIndex")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Explanation")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("OptionsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SourceChunkId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("QuizQuestions");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.RoleDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("RoleDefinitions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 6, 11, 11, 18, 38, 809, DateTimeKind.Utc).AddTicks(790),
                            Description = "Global platform owner with full operational control.",
                            DisplayName = "Super Admin",
                            IsActive = true,
                            IsDeleted = false,
                            IsSystemRole = true,
                            Name = "SuperAdmin"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 6, 11, 11, 18, 38, 809, DateTimeKind.Utc).AddTicks(790),
                            Description = "Manages one school, its users, content, and operations.",
                            DisplayName = "School Admin",
                            IsActive = true,
                            IsDeleted = false,
                            IsSystemRole = true,
                            Name = "SchoolAdmin"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 6, 11, 11, 18, 38, 809, DateTimeKind.Utc).AddTicks(800),
                            Description = "Creates learning content and supports study workflows.",
                            DisplayName = "Teacher",
                            IsActive = true,
                            IsDeleted = false,
                            IsSystemRole = true,
                            Name = "Teacher"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 6, 11, 11, 18, 38, 809, DateTimeKind.Utc).AddTicks(800),
                            Description = "Learner workspace for study materials and practice.",
                            DisplayName = "Student",
                            IsActive = true,
                            IsDeleted = false,
                            IsSystemRole = true,
                            Name = "Student"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 6, 11, 11, 18, 38, 809, DateTimeKind.Utc).AddTicks(800),
                            Description = "Guardian view into school learning content.",
                            DisplayName = "Parent",
                            IsActive = true,
                            IsDeleted = false,
                            IsSystemRole = true,
                            Name = "Parent"
                        });
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CanApprove")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanCreate")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanDelete")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanEdit")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanView")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.Property<Guid?>("RoleDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RoleDefinitionId", "Module")
                        .IsUnique();

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            CanApprove = true,
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            CreatedAt = new DateTime(2026, 6, 11, 11, 18, 38, 809, DateTimeKind.Utc).AddTicks(670),
                            IsDeleted = false,
                            Module = "Dashboard",
                            Role = "SuperAdmin",
                            RoleDefinitionId = new Guid("30000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            CanApprove = true,
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            CreatedAt = new DateTime(2026, 6, 11, 11, 18, 38, 809, DateTimeKind.Utc).AddTicks(680),
                            IsDeleted = false,
                            Module = "Schools",
                            Role = "SuperAdmin",
                            RoleDefinitionId = new Guid("30000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            CanApprove = true,
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            CreatedAt = new DateTime(2026, 6, 11, 11, 18, 38, 809, DateTimeKind.Utc).AddTicks(680),
                            IsDeleted = false,
                            Module = "Users",
                            Role = "SuperAdmin",
                            RoleDefinitionId = new Guid("30000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            CanApprove = true,
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            CreatedAt = new DateTime(2026, 6, 11, 11, 18, 38, 809, DateTimeKind.Utc).AddTicks(680),
                            IsDeleted = false,
                            Module = "Roles",
                            Role = "SuperAdmin",
                            RoleDefinitionId = new Guid("30000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            CanApprove = true,
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            CreatedAt = new DateTime(2026, 6, 11, 11, 18, 38, 809, DateTimeKind.Utc).AddTicks(690),
                            IsDeleted = false,
                            Module = "Articles",
                            Role = "SuperAdmin",
                            RoleDefinitionId = new Guid("30000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            CanApprove = true,
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            CreatedAt = new DateTime(2026, 6, 11, 11, 18, 38, 809, DateTimeKind.Utc).AddTicks(700),
                            IsDeleted = false,
                            Module = "Categories",
                            Role = "SuperAdmin",
                            RoleDefinitionId = new Guid("30000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            CanApprove = false,
                            CanCreate = false,
                            CanDelete = false,
                            CanEdit = false,
                            CanView = true,
                            CreatedAt = new DateTime(2026, 6, 11, 11, 18, 38, 809, DateTimeKind.Utc).AddTicks(710),
                            IsDeleted = false,
                            Module = "Dashboard",
                            Role = "SchoolAdmin",
                            RoleDefinitionId = new Guid("30000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            CanApprove = false,
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            CreatedAt = new DateTime(2026, 6, 11, 11, 18, 38, 809, DateTimeKind.Utc).AddTicks(710),
                            IsDeleted = false,
                            Module = "Users",
                            Role = "SchoolAdmin",
                            RoleDefinitionId = new Guid("30000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            CanApprove = false,
                            CanCreate = false,
                            CanDelete = false,
                            CanEdit = false,
                            CanView = true,
                            CreatedAt = new DateTime(2026, 6, 11, 11, 18, 38, 809, DateTimeKind.Utc).AddTicks(710),
                            IsDeleted = false,
                            Module = "Roles",
                            Role = "SchoolAdmin",
                            RoleDefinitionId = new Guid("30000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000010"),
                            CanApprove = true,
                            CanCreate = true,
                            CanDelete = false,
                            CanEdit = true,
                            CanView = true,
                            CreatedAt = new DateTime(2026, 6, 11, 11, 18, 38, 809, DateTimeKind.Utc).AddTicks(720),
                            IsDeleted = false,
                            Module = "Articles",
                            Role = "SchoolAdmin",
                            RoleDefinitionId = new Guid("30000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000011"),
                            CanApprove = false,
                            CanCreate = true,
                            CanDelete = false,
                            CanEdit = true,
                            CanView = true,
                            CreatedAt = new DateTime(2026, 6, 11, 11, 18, 38, 809, DateTimeKind.Utc).AddTicks(720),
                            IsDeleted = false,
                            Module = "Categories",
                            Role = "SchoolAdmin",
                            RoleDefinitionId = new Guid("30000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000012"),
                            CanApprove = false,
                            CanCreate = false,
                            CanDelete = false,
                            CanEdit = false,
                            CanView = true,
                            CreatedAt = new DateTime(2026, 6, 11, 11, 18, 38, 809, DateTimeKind.Utc).AddTicks(730),
                            IsDeleted = false,
                            Module = "Dashboard",
                            Role = "Teacher",
                            RoleDefinitionId = new Guid("30000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000013"),
                            CanApprove = false,
                            CanCreate = true,
                            CanDelete = false,
                            CanEdit = true,
                            CanView = true,
                            CreatedAt = new DateTime(2026, 6, 11, 11, 18, 38, 809, DateTimeKind.Utc).AddTicks(730),
                            IsDeleted = false,
                            Module = "Articles",
                            Role = "Teacher",
                            RoleDefinitionId = new Guid("30000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000014"),
                            CanApprove = false,
                            CanCreate = false,
                            CanDelete = false,
                            CanEdit = false,
                            CanView = true,
                            CreatedAt = new DateTime(2026, 6, 11, 11, 18, 38, 809, DateTimeKind.Utc).AddTicks(730),
                            IsDeleted = false,
                            Module = "Categories",
                            Role = "Teacher",
                            RoleDefinitionId = new Guid("30000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000015"),
                            CanApprove = false,
                            CanCreate = false,
                            CanDelete = false,
                            CanEdit = false,
                            CanView = true,
                            CreatedAt = new DateTime(2026, 6, 11, 11, 18, 38, 809, DateTimeKind.Utc).AddTicks(740),
                            IsDeleted = false,
                            Module = "Dashboard",
                            Role = "Student",
                            RoleDefinitionId = new Guid("30000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000016"),
                            CanApprove = false,
                            CanCreate = false,
                            CanDelete = false,
                            CanEdit = false,
                            CanView = true,
                            CreatedAt = new DateTime(2026, 6, 11, 11, 18, 38, 809, DateTimeKind.Utc).AddTicks(740),
                            IsDeleted = false,
                            Module = "Articles",
                            Role = "Student",
                            RoleDefinitionId = new Guid("30000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000017"),
                            CanApprove = false,
                            CanCreate = false,
                            CanDelete = false,
                            CanEdit = false,
                            CanView = true,
                            CreatedAt = new DateTime(2026, 6, 11, 11, 18, 38, 809, DateTimeKind.Utc).AddTicks(750),
                            IsDeleted = false,
                            Module = "Categories",
                            Role = "Student",
                            RoleDefinitionId = new Guid("30000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000018"),
                            CanApprove = false,
                            CanCreate = false,
                            CanDelete = false,
                            CanEdit = false,
                            CanView = true,
                            CreatedAt = new DateTime(2026, 6, 11, 11, 18, 38, 809, DateTimeKind.Utc).AddTicks(750),
                            IsDeleted = false,
                            Module = "Dashboard",
                            Role = "Parent",
                            RoleDefinitionId = new Guid("30000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000019"),
                            CanApprove = false,
                            CanCreate = false,
                            CanDelete = false,
                            CanEdit = false,
                            CanView = true,
                            CreatedAt = new DateTime(2026, 6, 11, 11, 18, 38, 809, DateTimeKind.Utc).AddTicks(750),
                            IsDeleted = false,
                            Module = "Articles",
                            Role = "Parent",
                            RoleDefinitionId = new Guid("30000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000020"),
                            CanApprove = false,
                            CanCreate = false,
                            CanDelete = false,
                            CanEdit = false,
                            CanView = true,
                            CreatedAt = new DateTime(2026, 6, 11, 11, 18, 38, 809, DateTimeKind.Utc).AddTicks(760),
                            IsDeleted = false,
                            Module = "Categories",
                            Role = "Parent",
                            RoleDefinitionId = new Guid("30000000-0000-0000-0000-000000000005")
                        });
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.School", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Board")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SubscriptionExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SubscriptionStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Schools");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            ApprovalStatus = "Approved",
                            Board = "CBSE",
                            City = "Srinagar",
                            CreatedAt = new DateTime(2026, 6, 11, 11, 18, 38, 809, DateTimeKind.Utc).AddTicks(410),
                            Email = "demo@codestrix.com",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "CodeStrix Demo School",
                            Plan = "Pro",
                            State = "J&K",
                            SubscriptionExpiresAt = new DateTime(2027, 6, 11, 11, 18, 38, 809, DateTimeKind.Utc).AddTicks(400),
                            SubscriptionStatus = "Active",
                            Type = "Private"
                        });
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("GradeLevel")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("GuardianName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("GuardianPhone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RollNumber")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<Guid?>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("SchoolId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            ApprovalStatus = "Approved",
                            CreatedAt = new DateTime(2026, 6, 11, 11, 18, 38, 809, DateTimeKind.Utc).AddTicks(480),
                            Email = "admin@vidyaai.com",
                            EmailVerified = true,
                            FirstName = "Super",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Admin",
                            PasswordHash = "$2a$11$RIzKRlsKF6lh3k9LHQHsROIDjily/9oaxg5wL8JSVdSxmBRQv7WVm",
                            Role = "SuperAdmin",
                            SchoolId = new Guid("00000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            ApprovalStatus = "Approved",
                            CreatedAt = new DateTime(2026, 6, 11, 11, 18, 38, 809, DateTimeKind.Utc).AddTicks(490),
                            Email = "schooladmin@vidyaai.com",
                            EmailVerified = true,
                            FirstName = "Aaliya",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Khan",
                            PasswordHash = "$2a$11$RIzKRlsKF6lh3k9LHQHsROIDjily/9oaxg5wL8JSVdSxmBRQv7WVm",
                            Role = "SchoolAdmin",
                            SchoolId = new Guid("00000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            ApprovalStatus = "Approved",
                            CreatedAt = new DateTime(2026, 6, 11, 11, 18, 38, 809, DateTimeKind.Utc).AddTicks(490),
                            Email = "teacher@vidyaai.com",
                            EmailVerified = true,
                            FirstName = "Rohan",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Sharma",
                            PasswordHash = "$2a$11$RIzKRlsKF6lh3k9LHQHsROIDjily/9oaxg5wL8JSVdSxmBRQv7WVm",
                            Role = "Teacher",
                            SchoolId = new Guid("00000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            ApprovalStatus = "Approved",
                            CreatedAt = new DateTime(2026, 6, 11, 11, 18, 38, 809, DateTimeKind.Utc).AddTicks(490),
                            Email = "student@vidyaai.com",
                            EmailVerified = true,
                            FirstName = "Zoya",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Mir",
                            PasswordHash = "$2a$11$RIzKRlsKF6lh3k9LHQHsROIDjily/9oaxg5wL8JSVdSxmBRQv7WVm",
                            Role = "Student",
                            SchoolId = new Guid("00000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            ApprovalStatus = "Approved",
                            CreatedAt = new DateTime(2026, 6, 11, 11, 18, 38, 809, DateTimeKind.Utc).AddTicks(500),
                            Email = "parent@vidyaai.com",
                            EmailVerified = true,
                            FirstName = "Imran",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Mir",
                            PasswordHash = "$2a$11$RIzKRlsKF6lh3k9LHQHsROIDjily/9oaxg5wL8JSVdSxmBRQv7WVm",
                            Role = "Parent",
                            SchoolId = new Guid("00000000-0000-0000-0000-000000000002")
                        });
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.UserPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId", "CategoryId")
                        .IsUnique();

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.UserSchoolEnrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.HasIndex("UserId", "SchoolId", "Role")
                        .IsUnique();

                    b.ToTable("UserSchoolEnrollments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 6, 11, 11, 18, 38, 809, DateTimeKind.Utc).AddTicks(920),
                            EnrolledAt = new DateTime(2026, 6, 11, 11, 18, 38, 809, DateTimeKind.Utc).AddTicks(920),
                            IsDeleted = false,
                            IsPrimary = true,
                            Role = "SuperAdmin",
                            SchoolId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Status = "Active",
                            UserId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 6, 11, 11, 18, 38, 809, DateTimeKind.Utc).AddTicks(930),
                            EnrolledAt = new DateTime(2026, 6, 11, 11, 18, 38, 809, DateTimeKind.Utc).AddTicks(930),
                            IsDeleted = false,
                            IsPrimary = true,
                            Role = "SchoolAdmin",
                            SchoolId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Status = "Active",
                            UserId = new Guid("00000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 6, 11, 11, 18, 38, 809, DateTimeKind.Utc).AddTicks(930),
                            EnrolledAt = new DateTime(2026, 6, 11, 11, 18, 38, 809, DateTimeKind.Utc).AddTicks(930),
                            IsDeleted = false,
                            IsPrimary = true,
                            Role = "Teacher",
                            SchoolId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Status = "Active",
                            UserId = new Guid("00000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 6, 11, 11, 18, 38, 809, DateTimeKind.Utc).AddTicks(940),
                            EnrolledAt = new DateTime(2026, 6, 11, 11, 18, 38, 809, DateTimeKind.Utc).AddTicks(940),
                            IsDeleted = false,
                            IsPrimary = true,
                            Role = "Student",
                            SchoolId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Status = "Active",
                            UserId = new Guid("00000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 6, 11, 11, 18, 38, 809, DateTimeKind.Utc).AddTicks(940),
                            EnrolledAt = new DateTime(2026, 6, 11, 11, 18, 38, 809, DateTimeKind.Utc).AddTicks(940),
                            IsDeleted = false,
                            IsPrimary = true,
                            Role = "Parent",
                            SchoolId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Status = "Active",
                            UserId = new Guid("00000000-0000-0000-0000-000000000009")
                        });
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.Announcement", b =>
                {
                    b.HasOne("VidyaAI.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VidyaAI.Domain.Entities.School", "School")
                        .WithMany("Announcements")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("School");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.Article", b =>
                {
                    b.HasOne("VidyaAI.Domain.Entities.User", "Author")
                        .WithMany("Articles")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VidyaAI.Domain.Entities.Category", "Category")
                        .WithMany("Articles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VidyaAI.Domain.Entities.School", "School")
                        .WithMany("Articles")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Author");

                    b.Navigation("Category");

                    b.Navigation("School");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.ChatMessage", b =>
                {
                    b.HasOne("VidyaAI.Domain.Entities.ChatSession", "Session")
                        .WithMany("Messages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.ChatSession", b =>
                {
                    b.HasOne("VidyaAI.Domain.Entities.Material", "Material")
                        .WithMany("ChatSessions")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VidyaAI.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.Comment", b =>
                {
                    b.HasOne("VidyaAI.Domain.Entities.Article", "Article")
                        .WithMany("Comments")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VidyaAI.Domain.Entities.Comment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VidyaAI.Domain.Entities.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("ParentComment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.CommentLike", b =>
                {
                    b.HasOne("VidyaAI.Domain.Entities.Comment", "Comment")
                        .WithMany("CommentLikes")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VidyaAI.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.Delivery", b =>
                {
                    b.HasOne("VidyaAI.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VidyaAI.Domain.Entities.FlashcardSet", "FlashcardSet")
                        .WithMany()
                        .HasForeignKey("FlashcardSetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VidyaAI.Domain.Entities.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VidyaAI.Domain.Entities.Quiz", "Quiz")
                        .WithMany()
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VidyaAI.Domain.Entities.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedBy");

                    b.Navigation("FlashcardSet");

                    b.Navigation("Material");

                    b.Navigation("Quiz");

                    b.Navigation("School");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.Flashcard", b =>
                {
                    b.HasOne("VidyaAI.Domain.Entities.FlashcardSet", "Set")
                        .WithMany("Cards")
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Set");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.FlashcardSet", b =>
                {
                    b.HasOne("VidyaAI.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VidyaAI.Domain.Entities.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VidyaAI.Domain.Entities.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedBy");

                    b.Navigation("Material");

                    b.Navigation("School");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.LessonPlan", b =>
                {
                    b.HasOne("VidyaAI.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VidyaAI.Domain.Entities.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VidyaAI.Domain.Entities.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedBy");

                    b.Navigation("Material");

                    b.Navigation("School");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.Like", b =>
                {
                    b.HasOne("VidyaAI.Domain.Entities.Article", "Article")
                        .WithMany("Likes")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VidyaAI.Domain.Entities.User", "User")
                        .WithMany("Likes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.Material", b =>
                {
                    b.HasOne("VidyaAI.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VidyaAI.Domain.Entities.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VidyaAI.Domain.Entities.User", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("School");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.MaterialChunk", b =>
                {
                    b.HasOne("VidyaAI.Domain.Entities.Material", "Material")
                        .WithMany("Chunks")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.Narration", b =>
                {
                    b.HasOne("VidyaAI.Domain.Entities.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.NarrationSegment", b =>
                {
                    b.HasOne("VidyaAI.Domain.Entities.Narration", "Narration")
                        .WithMany("Segments")
                        .HasForeignKey("NarrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Narration");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.Notification", b =>
                {
                    b.HasOne("VidyaAI.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.Quiz", b =>
                {
                    b.HasOne("VidyaAI.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VidyaAI.Domain.Entities.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VidyaAI.Domain.Entities.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedBy");

                    b.Navigation("Material");

                    b.Navigation("School");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.QuizAttempt", b =>
                {
                    b.HasOne("VidyaAI.Domain.Entities.Quiz", "Quiz")
                        .WithMany("Attempts")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VidyaAI.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.QuizQuestion", b =>
                {
                    b.HasOne("VidyaAI.Domain.Entities.Quiz", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("VidyaAI.Domain.Entities.RoleDefinition", "RoleDefinition")
                        .WithMany()
                        .HasForeignKey("RoleDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("RoleDefinition");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.User", b =>
                {
                    b.HasOne("VidyaAI.Domain.Entities.School", "School")
                        .WithMany("Users")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("School");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.UserPreference", b =>
                {
                    b.HasOne("VidyaAI.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VidyaAI.Domain.Entities.User", "User")
                        .WithMany("Preferences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.UserSchoolEnrollment", b =>
                {
                    b.HasOne("VidyaAI.Domain.Entities.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VidyaAI.Domain.Entities.User", "User")
                        .WithMany("Enrollments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.Article", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Likes");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.Category", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.ChatSession", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.Comment", b =>
                {
                    b.Navigation("CommentLikes");

                    b.Navigation("Replies");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.FlashcardSet", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.Material", b =>
                {
                    b.Navigation("ChatSessions");

                    b.Navigation("Chunks");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.Narration", b =>
                {
                    b.Navigation("Segments");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.Quiz", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.School", b =>
                {
                    b.Navigation("Announcements");

                    b.Navigation("Articles");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("VidyaAI.Domain.Entities.User", b =>
                {
                    b.Navigation("Articles");

                    b.Navigation("Comments");

                    b.Navigation("Enrollments");

                    b.Navigation("Likes");

                    b.Navigation("Preferences");
                });
#pragma warning restore 612, 618
        }
    }
}
