// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using VidyaAI.Infrastructure.Data;

#nullable disable

namespace VidyaAI.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260703120000_AddSchoolDocument")]
    partial class AddSchoolDocument
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Minimal model snapshot required for EF tooling. Full model snapshot
            // is not necessary for applying this simple migration.
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");
        }
    }
}
